module.exports = {
    media: '/media',
    playlists: '/playlists',
    comments: '/comments',
    search: '/search',
    tags: '/tags',
    ridertags: '/tags/rider',
    horsetags: '/tags/horse',
    categories: '/categories',
    members: '/users',
    liked: '/user/action/like',
    history: '/user/action/watch',
    actions: '/actions',
    manage_media: '/manage_media',
    manage_users: '/manage_users',
    manage_comments: '/manage_comments',
};
