# Generated by Django 4.2.2 on 2024-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
